import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const login: NextPage = () => {
  const CLIENT_ID = "";
  const REDIRECT_URI =  "http://localhost:3000/kakaooauth";
  const KAKAO_AUTH_URL = `https://kauth.kakao.com/oauth/authorize?client_id=${CLIENT_ID}&redirect_uri=${REDIRECT_URI}&response_type=code`;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <a href={KAKAO_AUTH_URL} className={styles.card}>
            <h2>kakao Login &rarr;</h2>
          </a>
        </div>
      </main>
    </div>
  )
}

export default login
