import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const login2: NextPage = () => {
  const CLIENT_ID = process.env.KAKAO_REST_API_KEY;
  const REDIRECT_URI_2 =  process.env.KAKAO_REDIRECT_URI_2;
  const KAKAO_AUTH_URL = `${process.env.KAKAO_AUTH_URL}?client_id=${CLIENT_ID}&redirect_uri=${REDIRECT_URI_2}&response_type=code`;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <a href={KAKAO_AUTH_URL} className={styles.card}>
            <h2>kakao Login2 &rarr;</h2>
          </a>
        </div>
      </main>
    </div>
  )
}

export default login2
